### ISSUE TITLE
Number of clients always 0 which is wrong

### ISSUE THREAD

**Issue by dadosch** [Philhil/FfsNodeAlarm#2]
In the dashboard, it always shows 0 clients despite there are some (for the last ~18 hours) on the node which is also displayed on the FFS Map. 
If you need the node name, let me know.

**Comment by Philhil** [comment]
The counter shows actually only currently connected Clients (approx 5 mins old data). It is the same Data as the "Client" column at http://karte.freifunk-stuttgart.de/?tab=1

**Comment by dadosch** [comment]
Have a look at the screenshot
<removed>

(the number of clients didn't change in the past hour)

**Comment by Philhil** [comment]
There was a id bug when querry the correct task -> nodestat relation
Thanks for reporting the issue!
